### ISSUE TITLE
"LoRa initialization failed" line 140 ulora.py

### ISSUE THREAD

**Issue by anuareramirez** [martynwheeler/u-lora#4]
Why this could happened?

**Comment by atonughosh** [comment]
I have the same issue. I'm using ESP32 and RFM95W. ANy solution to this?

**Comment by anuareramirez** [comment]
I'm using the same, I already tried with Arduino IDE too, and the same error.

If someone have an answer I will appreciate it. Thanks

**Comment by anuareramirez** [comment]
I was trying to use it without soldering the RFM95, when I soldered it all resolved.
